name: C/C++ CI

on:
  create:
    tags:
    - v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: make
      run: make -j2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: registry.cn-hangzhou.aliyuncs.com # optional
          # Docker repository to tag the image with
          repository: rtshao/station
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true # optional
          # Path to the build context
          path: ./build/ # optional, default is .
